sed s#{{REACT_APP_ENGINE_HTTP_URL}}#"$AMP_ENGINE_HTTP_URL"#g template.js |
sed s#{{REACT_APP_ENGINE_WS_URL}}#"$AMP_ENGINE_WS_URL"#g |
sed s#{{REACT_APP_ETHEREUM_NODE_HTTP_URL}}#"$AMP_ETHEREUM_NODE_HTTP_URL"#g |
sed s#{{REACT_APP_ETHEREUM_NODE_WS_URL}}#"$AMP_ETHEREUM_NODE_WS_URL"#g |
sed s#{{REACT_APP_DEFAULT_NETWORK_ID}}#"$AMP_ETHEREUM_NETWORK_ID"#g > config.js
