import accountDomain from './account';
import accountBalancesDomain from './accountBalances';
import depositFormDomain from './depositForm';
import depthChartDomain from './depthChart';
import etherBalanceDomain from './etherBalance';
import etherTxDomain from './etherTx';
import tradingPageDomain from './tradingPage';
import loginPageDomain from './loginPage';
import ohlcvDomain from './ohlcv';
import orderBookDomain from './orderBook';
import orderFormDomain from './orderForm';
import orderHistoryDomain from './orderHistory';
import settingsDomain from './settings';
import signerDomain from './signer';
import tokenPairsDomain from './tokenPairs';
import tokenDomain from './tokens';
import tradeHistoryDomain from './tradeHistory';
import walletsDomain from './wallets';
import notificationsDomain from './notifications';

export const getAccountDomain = state => accountDomain(state.account);
export const getAccountBalancesDomain = state => accountBalancesDomain(state.accountBalances);
export const getDepositFormDomain = state => depositFormDomain(state.depositForm);
export const getDepthChartDomain = state => depthChartDomain(state.depthChart);
export const getEtherBalanceDomain = state => etherBalanceDomain(state.etherBalance);
export const getEtherTxDomain = state => etherTxDomain(state.etherTx);
export const getTradingPageDomain = state => tradingPageDomain(state.homePage);
export const getLoginPageDomain = state => loginPageDomain(state.loginPage);
export const getOhlcvDomain = state => ohlcvDomain(state.ohlcv);
export const getOrderBookDomain = state => orderBookDomain(state.orderBook);
export const getOrderFormDomain = state => orderFormDomain(state.orderForm);
export const getOrderHistoryDomain = state => orderHistoryDomain(state.orderHistory);
export const getSettingsDomain = state => settingsDomain(state.settings);
export const getSignerDomain = state => signerDomain(state.signer);
export const getTokenPairsDomain = state => tokenPairsDomain(state.tokenPairs);
export const getTokenDomain = state => tokenDomain(state.tokens);
export const getTradeHistoryDomain = state => tradeHistoryDomain(state.tradeHistory);
export const getWalletsDomain = state => walletsDomain(state.wallets);
export const getNotificationsDomain = state => notificationsDomain(state.notifications);
